postgresql: 
  host: int0.silverpeas.org
  inst: silvertest
  updt: SilverUpdate
  url: jdbc:postgresql://int0.silverpeas.org:5433
  driver: org.postgresql.Driver

mssql:
  host: int1.silverpeas.org
  inst: silvertest
  updt: SilverUpdate
  url: jdbc:jtds:sqlserver://int1.silverpeas.org:1433
  driver: net.sourceforge.jtds.jdbc.Driver

oracle:
  host: int3.silverpeas.org
  inst: SILVERTEST
  updt: SILVERUPDATE
  url: jdbc:oracle:thin:@int3.silverpeas.org:1521
  driver: oracle.jdbc.driver.OracleDriver

h2:
  host: localhost
  inst: SILVERTEST
  updt: SILVERUPDATE
  url: jdbc:h2:tcp://localhost:9092
  driver: org.h2.Driver
  