postgresql: 
  host: int0.silverpeas.org
  inst: silvertest
  updt: SilverUpdate
  url: jdbc:postgresql://int0.silverpeas.org:5433
  driver: org.postgresql.Driver

# encrypt=false is required: the Microsoft JDBC driver expects an encrypted connection by default
# since its version 10 whereas the SQL Server for the tests has no trusted certificate
mssql:
  host: int1.silverpeas.org
  inst: silvertest
  updt: SilverUpdate
  url: jdbc:sqlserver://int1.silverpeas.org:1433;encrypt=false
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver

oracle:
  host: int3.silverpeas.org
  inst: SILVERTEST
  updt: SILVERUPDATE
  url: jdbc:oracle:thin:@int3.silverpeas.org:1521
  driver: oracle.jdbc.driver.OracleDriver

h2:
  host: localhost
  inst: silvertest
  updt: SilverUpdate
  url: jdbc:h2:tcp://localhost:9092
  driver: org.h2.Driver
